name: 'Bump Versions'
description: 'This action bumps versions of Cargo.toml and _version.py file, matching release tag'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Bump Cargo version
      # python ./cargo_version_bumper.py --target Cargo.toml "${{ github.ref_name }}"
      run: |
        python .github/actions/bump_version/cargo_version_bumper.py --target Cargo.toml "0.0.1"
      shell: bash

#   - name: Check Cargo.toml version matches Release tag
#     run: |
#       CARGO_VERSION=$(grep '^version =' Cargo.toml | sed 's/.*"\(.*\)".*/\1/')
#       if [ "${GITHUB_REF#refs/tags/}" != "$CARGO_VERSION" ]; then
#         echo "Version mismatch: Cargo.toml ($CARGO_VERSION) doesn't match Release tag (${GITHUB_REF#refs/tags/})"
#         exit 1
#       fi
