name: Release PyPi

on:
  workflow_dispatch:
# release:
#   types:
#     - created
  pull_request:
    branches: [main]

jobs:
  build_wheels:
    # TODO: switch to main
    uses: dottxt-ai/outlines-core/.github/workflows/build_wheels.yml@maturin
    with:
      auto_bump: true

  release:
    needs: build_wheels
    name: Release to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          merge-multiple: true
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

  #     - name: Publish to PyPI
  #       uses: pypa/gh-action-pypi-publish@v1.5.0
  #       with:
  #         user: __token__
  #         password: ${{ secrets.PYPI_SECRET }}
